### ISSUE TITLE
Refactor Inline Parsing and add support for inputs with multiple modules

### ISSUE THREAD

**Issue by shashwatj07** [checkstyle/checkstyle#10745]
- [x] Rename TestInputConfiguration to ModuleInputConfiguration - #10746
- [x] Make new TestInputConfiguration to hold child modules and violations - #10750
- [x] Add functionality for module parent - #10754
- [x] Add inline support for tests with multiple modules - #10758 
- [x] Remove hardcoded config in test methods - #10758
