### ISSUE TITLE
Tracker for pitest-coding failures

### ISSUE THREAD

**Issue by nick-mancuso** [checkstyle/checkstyle#11427]
Since we have been seeing random (but regular) failures in `pitest-coding`, I thought it would be a good idea to track exactly which lines are causing pitest to fail. Maintainers, feel free to just add any failures that you notice below (in issue description).

- [x] `EqualsAvoidNullCheck.java.html:<td class='covered'><pre><span  class='survived'>            if (field.findFirstToken(TokenTypes.IDENT) != null) {</span></pre></td></tr>`

  https://nick-mancuso.github.io/pit-reports-equal/202203230810/com.puppycrawl.tools.checkstyle.checks.coding/EqualsAvoidNullCheck.java.html

  Negated conditional

- [x] `RequireThisCheck.java.html:<td class='covered'><pre><span  class='survived'>            if (returnedVariable) {</span></pre></td></tr>`

  Report at https://nick-mancuso.github.io/pit-reports-requirethis/202203211238/com.puppycrawl.tools.checkstyle.checks.coding/RequireThisCheck.java.html

  Removed  conditional

- [x] `CheckstyleAntTask.java.html:<td class='covered'><pre><span  class='survived'>            if (toFile == null || !useFile) {</span></pre></td></tr>`

  https://pbludov.github.io/pitest-ant-coverage-report/pit-reports/202203270532/com.puppycrawl.tools.checkstyle.ant/CheckstyleAntTask.java.html#org.pitest.mutationtest.report.html.SourceFile@352b92be_720

  removed conditional - replaced equality check with true → SURVIVED

Hopefully we can diagnose issue and make `pitest-coding` more stable.

**Comment by rnveach** [comment]
It may be helpful to know which mutator is the issue as we have added multiple and one line can have multiple mutators involved. In the current example we could be mutating `findFirstToken` or we could be mutating the entire condition to true/false. We may have to look into how we can add this to the report.

**Comment by nick-mancuso** [comment]
In the case of `RequireThisCheck`:

Passing `pitest-coding`:
```
org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_ELSE
>> Generated 904 Killed 894 (99%)
> KILLED 881 SURVIVED 10 TIMED_OUT 13 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 

```

Failing `pitest-coding`:
```
org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_EQUAL_ELSE
>> Generated 904 Killed 893 (99%)
> KILLED 880 SURVIVED 11 TIMED_OUT 13 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 

```

**Comment by rnveach** [comment]
> we have been seeing random (but regular) 
> that perhaps bytecode had changed

It is not a constant issue. We would have to examine the bytecode between the failing and passing pitest. Pitest only deals with the bytecode, so it could be specific bytecode being generated that is the reason for the failures.

**Comment by romani** [comment]
Does anybody can reproduce this on local ? If not, it might be jdk specific issue and we can try to use container with different jdk.

**Comment by rnveach** [comment]
Just a note on expanding pitest reporting, pitest does support other formats besides HTML if the HTML parsing is blocking us. Pitest also supports XML and CSV. Looking at the XML format though and it does not provide a snippet of the source code similar to the HTML and our current reporting.

**Comment by Vyom-Yadav** [comment]
> It may be helpful to know which mutator is the issue as we have added multiple and one line can have multiple mutators involved

For `EqualsAvoidNullCheck.java.html:<td class='covered'><pre><span class='survived'> if (field.findFirstToken(TokenTypes.IDENT) != null) {</span></pre></td></tr>` it is [REMOVE_CONDITIONALS](https://pitest.org/quickstart/mutators/#REMOVE_CONDITIONALS), it changed the condition to `true` and the mutation survived.

This mutation might not be associated with the JDK version, the method-
```java
public void addField(DetailAST field) {                  
    if (field.findFirstToken(TokenTypes.IDENT) != null) {
        fields.add(field);                               
    }                                                    
}                                                        
```
adds a field, the instance variable `fields` is defined as-
```java
private final Set<DetailAST> fields = new HashSet<>();
```
This `fields` variable is iterated in-
```java
public DetailAST findField(String name) {      
    DetailAST resultField = null;              
    for (DetailAST field: fields) {            
        if (getFieldName(field).equals(name)) {
            resultField = field;               
            break;                             
        }                                      
    }                                          
    return resultField;                        
}                                              
```
Now being a HashSet, it does not maintain any order, so there might be a chance that we might break from the loop earlier, before hitting the exception condition and none of the tests fail. I analyzed the Input file a bit and have come to the conclusion that this is possible. I have experienced this type of pitest failure earlier also, and am quite certain that changing this to a LinkedHashSet should solve the problem. I will make a PR and let's see how pitest behaves.

**Comment by nick-mancuso** [comment]
@pbludov I have not seen unstable mutation in CheckstyleAntTask for some time now. Are you good to close this issue?

**Comment by Vyom-Yadav** [comment]
@nick-mancuso The mutation above has been addressed, can we close this?

**Comment by nick-mancuso** [comment]
> @nick-mancuso The mutation above has been addressed, can we close this?

please share link to PR where we killed this mutation

**Comment by nick-mancuso** [comment]
Closed via https://github.com/checkstyle/checkstyle/pull/11890
