### ISSUE TITLE
Resolve pitest survivals in modules - 5

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#13809]
Split from 13321
Part of https://github.com/checkstyle/checkstyle/issues/13089

# 4) [Pitest-Filters](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-filters-suppressions.xml)

**1) SuppressionCommentFilter**

- [x] NonVoidMethodCallMutator (1) 
        https://github.com/checkstyle/checkstyle/pull/13833

------------

 **3) SuppressFilterElement**
 
- [x] NonVoidMethodCallMutator (3)
        https://github.com/checkstyle/checkstyle/pull/13841 (Covered 3 mutation)
- [x] MemberVariableMutator (6)   
       https://github.com/checkstyle/checkstyle/pull/13841 (Covered 6 Mutation)

-----------
 
**5) SuppressWithPlainTextCommentFilter**
 
- [x] NonVoidMethodCallMutator (2)
       https://github.com/checkstyle/checkstyle/pull/13888
       
-------
 
**7) XpathFilterElement**

- [x] NonVoidMethodCallMutator (3)
      https://github.com/checkstyle/checkstyle/pull/13841 (Covered 3 Mutation)
- [x] MemberVariableMutator (3) 
       https://github.com/checkstyle/checkstyle/pull/13841 (Covered 3 Mutation)
- [x] MemberVariableMutator (7)
https://github.com/checkstyle/checkstyle/pull/13841 (Covered 7 mutation) 
 
----------
 
**8) SuppressWithPlainTextCommentFilter$Suppression**
 
- [x] MemberVariableMutator (2)
       https://github.com/checkstyle/checkstyle/pull/13888
       
-------------

# 6) [Pitest-Common](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-common-suppressions.xml)

**1) PackageObjectFactory**

some related issue https://github.com/checkstyle/checkstyle/issues/11902

- [x] NonVoidMethodCallMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13924
- [x] RemoveConditionalMutator_EQUAL_IF (2)
       https://github.com/checkstyle/checkstyle/pull/13924 
- [x] NakedReceiverMutator (1)
        https://github.com/checkstyle/checkstyle/pull/13927 

-----------

**3) ConfigurationLoader$InternalLoader**

- [x] ArgumentPropagationMutator (1)
        https://github.com/checkstyle/checkstyle/pull/13899
- [x] NonVoidMethodCallMutator (2)
        https://github.com/checkstyle/checkstyle/pull/13899
        https://github.com/checkstyle/checkstyle/pull/13900
        
-------------

**5) Checker**

- [x] NonVoidMethodCallMutator (2)
       https://github.com/checkstyle/checkstyle/pull/13914
       https://github.com/checkstyle/checkstyle/pull/13981
- [x] NakedReceiverMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13913

--------

**6) AuditEventDefaultFormatter**

- [x] ArgumentPropagationMutator (1)
      https://github.com/checkstyle/checkstyle/pull/13826
- [x] NonVoidMethodCallMutator (2)
       https://github.com/checkstyle/checkstyle/pull/13826 (Covered 2 mutation)

---------

# 7) [Pitest-Utils](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-utils-suppressions.xml)

**1) JavadocUtil**

- [x] NonVoidMethodCallMutator (1)
        https://github.com/checkstyle/checkstyle/pull/13477
--------

**2) XpathUtil**

- [x] NakedReceiverMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13944
 
**4) CommonUtil**

- [x] RemoveConditionalMutator_EQUAL_IF (1)
       https://github.com/checkstyle/checkstyle/pull/13948

--------

**5) TokenUtil**

- [x] NonVoidMethodCallMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13943

----------

# 9) [Pitest-tree-walker](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-tree-walker-suppressions.xml)

   
-----------
 
**2) TreeWalker**

- [x] NakedReceiverMutator (3)
       https://github.com/checkstyle/checkstyle/pull/13928
       https://github.com/checkstyle/checkstyle/pull/13975 

# 5) [Pitest-common-2](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-common-2-suppressions.xml)

**1) JavaParser**

- [x] VoidMethodCallMutator (1)
       This mutation will cover at https://github.com/checkstyle/checkstyle/issues/12186

--------------

**2) JavadocPropertiesGenerator**

- [x] NonVoidMethodCallMutator (1)
        https://github.com/checkstyle/checkstyle/pull/13821
- [x] NakedReceiverMutator (1)
      https://github.com/checkstyle/checkstyle/pull/13870

------

**3) XmlLoader**

- [x] NonVoidMethodCallMutator (1)
      https://github.com/checkstyle/checkstyle/pull/13804

--------------

# 1) [Pitest-Import](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-imports-suppressions.xml)

**2) FileImportControl**
- [x] https://github.com/checkstyle/checkstyle/pull/13760

-------

# 2) [Pitest-coding-2](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-coding-2-suppressions.xml)

**1) FinalLocalVariableCheck**

- [x] NonVoidMethodCallMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13184  (on @rdiachenko )

--------

**2) UnusedLocalVariableCheck**

- [x] NakedReceiverMutator (1)
      https://github.com/checkstyle/checkstyle/pull/13151 (on @Vyom-Yadav  )

--------
 
# 8) [Pitest-api](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-api-suppressions.xml)

**1) Violation**

- [x] NonVoidMethodCallMutator (1)
       https://github.com/checkstyle/checkstyle/pull/13810

# 3) [Pitest-Xpath](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-xpath-suppressions.xml)

**3) RootNode**

- [x] NonVoidMethodCallMutator (1)
        https://github.com/checkstyle/checkstyle/pull/13817
- [x] PrimitiveReturnsMutator (1)
        https://github.com/checkstyle/checkstyle/pull/13817

**5) AbstractRootNode**

- [x] RemoveSwitchMutator_2 (1)
       https://github.com/checkstyle/checkstyle/pull/13818

-------------

**Comment by romani** [comment]
Leftovers are moved to https://github.com/checkstyle/checkstyle/issues/14019

**Comment by romani** [comment]
# 1) [Pitest-Filters](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-filters-suppressions.xml)

-------

**1) SuppressFilterElement**

- [ ] MemberVariableMutator (10)     `10 mutations delayed until hcoles/pitest#1230`

----------

**2 SuppressWithNearbyCommentFilter$Tag**

- [ ] MemberVariableMutator (2)  `2 mutations delayed until hcoles/pitest#1230`
 
--------

**3) SuppressWithPlainTextCommentFilter$Suppression**
 
- [ ] MemberVariableMutator (2) `2 mutations delayed until hcoles/pitest#1230`

-----------
 
**10) SuppressionCommentFilter$Tag**
 
- [ ] MemberVariableMutator (2) `2 mutations delayed until hcoles/pitest#1230`

# 2) [Pitest-Common](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-common-suppressions.xml)

**4) LocalizedMessage**

- [ ] MemberVariableMutator (1) `delayed until hcoles/pitest#1230`


# 3) [Pitest-Import](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-imports-suppressions.xml)

**1) PkgImportControl**

- [ ] MemberVariableMutator (3)  ---     `all are delayed until hcoles/pitest#1230`

**2) FileImportControl**

- [ ] MemberVariableMutator (1) `delayed until hcoles/pitest#1230`

# 4) [Pitest-api](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-api-suppressions.xml)

**1) Violation**

- [ ] MemberVariableMutator (1)   `delayed until hcoles/pitest#1230`

**2) FileText**

- [ ] MemberVariableMutator (1)       -->   `delayed until hcoles/pitest#1230`

-------

# 5) [Pitest-Xpath](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-xpath-suppressions.xml)


**1) FollowingIterator**

- [ ] MemberVariableMutator (1) `delayed until hcoles/pitest#1230`

---------

**2) ReverseListIterator**

- [ ] memberVariableMutator (1) `delayed until hcoles/pitest#1230`

-----------


**3) PrecedingIterator**

- [ ] MemberVariableMutator (1) `delayed until hcoles/pitest#1230`
