### ISSUE TITLE
Resolve pitest survivals in modules

### ISSUE THREAD

**Issue by Kevin222004** [checkstyle/checkstyle#14019]
# 1) [Pitest-Filters](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-filters-suppressions.xml)

-------

**1) SuppressWithNearbyCommentFilter**

- [ ] NonVoidMethodCallMutator (1)

-------
 
**2) SuppressWithNearbyTextFilter**

some details at https://github.com/checkstyle/checkstyle/issues/12952
 
- [ ] NonVoidMethodCallMutator (1)
- [ ] RemoveConditionalMutator_EQUAL_IF (1)
 
--------

**3) XpathFilterElement**

- [ ] ArgumentPropagationMutator (1)
- [ ] NonVoidMethodCallMutator (1)
- [ ] NakedReceiverMutator (1)

-----------

**4) SuppressionXpathSingleFilter** 
 
- [ ] MemberVariableMutator (1) https://github.com/checkstyle/checkstyle/pull/13794
- [ ] MemberVariableMutator (1) should be fixed similar as above
- [ ] MemberVariableMutator (1) should be fixed similar as above

-------------

--------------------------------------

# MemberVariableMutator all are delayed until hcoles/pitest#1230

# 4) [Pitest-Filters](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-filters-suppressions.xml)

-------

**1) SuppressFilterElement**

- [ ] MemberVariableMutator (10)     `10 mutations delayed until hcoles/pitest#1230`

----------

**2 SuppressWithNearbyCommentFilter$Tag**

- [ ] MemberVariableMutator (2)  `2 mutations delayed until hcoles/pitest#1230`
 
--------

**3) SuppressWithPlainTextCommentFilter$Suppression**
 
- [ ] MemberVariableMutator (2) `2 mutations delayed until hcoles/pitest#1230`

--------

**Comment by suniti0804** [comment]
I worked on ScopeUtil#getScopeFromMods

**Comment by piyush-1234** [comment]
i am on ModuleReflectionUtil#getCheckstyleModules

**Comment by Zopsss** [comment]
I'm working on  `NonVoidMethodCallMutator on this.severity = SeverityLevel.getInstance(severity);` &  `MemberVariableMutator on this.severity = SeverityLevel.getInstance(severity);` of `Checker`

**Comment by mahfouz72** [comment]
i am on `for (DetailAST token = node.getParent();` of scopeUtil

**Comment by mahfouz72** [comment]
I am on  `.filter(ModuleReflectionUtil::isCheckstyleModule)`

**Comment by MohanadKh03** [comment]
I am on ``ArgumentPropagationMutator on final String stripped = CommonUtil.relativizePath(basedir, fileName);``

**Comment by romani** [comment]
@kkoutsilis , can you help us with one case from this issue?  Thanks a lot in advance.

**Comment by kkoutsilis** [comment]
Hey @romani, I will have a look, thanks 🙂

**Comment by kkoutsilis** [comment]
Hey @romani I am trying to understand the process of killing a mutation, as this is a new concept for me and I am wondering if the steps mentioned in https://github.com/checkstyle/checkstyle/issues/13999#issue-1979667444 are relevant to this issue as well?

**Comment by romani** [comment]
@kkoutsilis , yes, but this is just list of ideas to start with if you have no ideas.
You can choose any and create PR and we will go deeper together.

**Comment by zyadahmed** [comment]
@romani Hi Romani, I have a question about TreeWalker `.thenComparing(AbstractCheck::getId)`.  My idea is to create a test case with multiple checks having the same name but different IDs.  
 The order of violation generation should match the order that the method generates.  
 However, this approach is not killing the mutation in Pitest (it still survives).  
 Do you think this is the correct approach, or is there a better way to ensure the mutation is detected?

**Comment by Mostafahassen1** [comment]
I am on `RemoveConditionalMutator_EQUAL_IF on parent.getParent().getType() == memberType`

**Comment by romani** [comment]
>Do you think this is the correct approach, or is there a better way to ensure the mutation is detected?

If mutation is not deleted, it is not good enough approach. Try to analyze it more.

**Comment by Harsh-Agrawal96** [comment]
I am on `NonVoidMethodCallMutator on int length = inputStream.read(buffer)` under `SarifLogger`

**Comment by zyadahmed** [comment]
I am on  XMLLogger `ArgumentPropagationMutator on fileMessages.remove(fileName);`

**Comment by aboro-code** [comment]
Hi i am on `NakedReceiverMutator on .thenComparing(AbstractCheck::getId`

**Comment by zyadahmed** [comment]
I am on `SuppressWithNearbyTextFilter` `if (!cachedFileAbsolutePath.equals(eventFileTextAbsolutePath))`

**Comment by ahmedyoussefg** [comment]
I am on `NonVoidMethodCallMutator` on `htmlTagNameStart = stack.pop()` in `JavadocDetailNodeParser`

**Comment by zyadahmed** [comment]
I am on `SuppressionsStringPrinter`  `final FileText fileText = new FileText(file.getAbsoluteFile`

**Comment by SteLeo1602** [comment]
I am on `NonVoidMethodCallMutator on return &quot;Checkstyle version: &quot; + Main.class.getPackage().getImplementationVersion`

**Comment by SteLeo1602** [comment]
I am on `ArgumentPropagationMutator on writer.print(encode(event.getModuleId()))`

**Comment by SteLeo1602** [comment]
I am on `ArgumentPropagationMutator on writer.print(encode(event.getSourceName())`

**Comment by SteLeo1602** [comment]
I am on `NonVoidMethodCallMutator on + Main.class.getPackage().getImplementationVersion`

**Comment by Mostafahassen1** [comment]
i'm on `SuppressionXpathSingleFilter,  MemberVariableMutator on this.message = null; should be fixed by similar test as in above PR`

**Comment by SteLeo1602** [comment]
I'm on `NonVoidMethodCallMutator on final String version = SarifLogger.class.getPackage().getImplementationVersion();`

**Comment by SteLeo1602** [comment]
I'm on `
NonVoidMethodCallMutator on final String version = XMLLogger.class.getPackage().getImplementationVersion();`

**Comment by SteLeo1602** [comment]
I'm on `ArgumentPropagationMutator on + encode(event.getMessage())`

**Comment by Brijeshthummar02** [comment]
@Kevin222004 while going through issue found below completed but unable to fetch in issue description

![Image](https://github.com/user-attachments/assets/3e3b0227-177f-485f-8966-01194e7fd6ea)

As i see in "com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java" ```this.message = null;``` is covered in testcase

```

    /**
     * This test is required to cover pitest mutation
     * for reset of 'message' field in SuppressionXpathSingleFilter.
     * This not possible to reproduce by natural execution of Checkstyle
     * as config is never changed in runtime.
     * Projects that use us by api can reproduce this case.
     * We need to allow users to reset module property to default state.
     *
     * @throws Exception when there is problem to load Input file
     */

    @Test
    public void testSetMessageHandlesNullCorrectly() throws Exception {
        final File file = new File(getPath("InputSuppressionXpathSingleFilterComplexQuery.java"));

        final SuppressionXpathSingleFilter filter = new SuppressionXpathSingleFilter();
        filter.setMessage("MagicNumber");
        filter.finishLocalSetup();

        final Violation violation = new Violation(27, 21, TokenTypes.NUM_DOUBLE, "",
                "", null, null, null,
                MagicNumberCheck.class, "MagicNumber");

        final FileContents fileContents =
                new FileContents(new FileText(file, StandardCharsets.UTF_8.name()));

        final TreeWalkerAuditEvent ev = new TreeWalkerAuditEvent(fileContents, file.getName(),
                violation, JavaParser.parseFile(file, JavaParser.Options.WITHOUT_COMMENTS));

        assertWithMessage("match is expected as 'message' is set")
                .that(filter.accept(ev))
                .isFalse();

        filter.setMessage(null);
        filter.finishLocalSetup();

        assertWithMessage("no match is expected as whole filter is defaulted (empty)")
                .that(filter.accept(ev))
                .isTrue();
    }
```

**Comment by Brijeshthummar02** [comment]
> [@Kevin222004](https://github.com/Kevin222004) while going through issue found below completed but unable to fetch in issue description
> 
> ![Image](https://github.com/user-attachments/assets/3e3b0227-177f-485f-8966-01194e7fd6ea)
> 
> As i see in "com/puppycrawl/tools/checkstyle/filters/SuppressionXpathSingleFilterTest.java" `this.message = null;` is covered in testcase
> 
> ```
> 
>     /**
>      * This test is required to cover pitest mutation
>      * for reset of 'message' field in SuppressionXpathSingleFilter.
>      * This not possible to reproduce by natural execution of Checkstyle
>      * as config is never changed in runtime.
>      * Projects that use us by api can reproduce this case.
>      * We need to allow users to reset module property to default state.
>      *
>      * @throws Exception when there is problem to load Input file
>      */
> 
>     @Test
>     public void testSetMessageHandlesNullCorrectly() throws Exception {
>         final File file = new File(getPath("InputSuppressionXpathSingleFilterComplexQuery.java"));
> 
>         final SuppressionXpathSingleFilter filter = new SuppressionXpathSingleFilter();
>         filter.setMessage("MagicNumber");
>         filter.finishLocalSetup();
> 
>         final Violation violation = new Violation(27, 21, TokenTypes.NUM_DOUBLE, "",
>                 "", null, null, null,
>                 MagicNumberCheck.class, "MagicNumber");
> 
>         final FileContents fileContents =
>                 new FileContents(new FileText(file, StandardCharsets.UTF_8.name()));
> 
>         final TreeWalkerAuditEvent ev = new TreeWalkerAuditEvent(fileContents, file.getName(),
>                 violation, JavaParser.parseFile(file, JavaParser.Options.WITHOUT_COMMENTS));
> 
>         assertWithMessage("match is expected as 'message' is set")
>                 .that(filter.accept(ev))
>                 .isFalse();
> 
>         filter.setMessage(null);
>         filter.finishLocalSetup();
> 
>         assertWithMessage("no match is expected as whole filter is defaulted (empty)")
>                 .that(filter.accept(ev))
>                 .isTrue();
>     }
> ```
> 
> Also mutation related to it in "pitest-filters-suppressions.xml" is not found means it is killed.

@romani Follow up on this.

**Comment by romani** [comment]
I marked it as done/checked.

**Comment by romani** [comment]
@Hariom-kr, please help us here.
Pitest is primary quality measurement in our project, let get familiar with it.

**Comment by ivamly** [comment]
I am on ModifiedControlVariableCheck.java in [pitest-coding-2-suppressions.xml](https://github.com/checkstyle/checkstyle/blob/master/config/pitest-suppressions/pitest-coding-2-suppressions.xml)

**Comment by romani** [comment]
close in favor of sub issues of https://github.com/checkstyle/checkstyle/issues/12341
