### ISSUE TITLE
Add Check Support for Java 21 Record Pattern Syntax 

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14890]
This issue will be the main tracker of all the work related to [Record Pattern](https://openjdk.org/jeps/440). It aims to support the new record pattern syntax introduced in Java 21. It will involve updating existing checks to ensure they correctly handle this new syntax and analysis of possible static analysis coverage (new checks) for this new language feature.

--------------------------------------------------------------------
  **AST view:** https://github.com/checkstyle/checkstyle/wiki/Record-Pattern-Preview---AST-strucuture
 **New tokens:**  `RECORD_PATTERN_DEF`,  `RECORD_PATTERN_COMPONENTS`
  **Similar/Related tokens and constructs:** `PATTERN_VARIABLE_DEF`, `PATTERN_DEF`, `LITERAL_INSTANCEOF`, `RECORD_COMPONENT_DEF`, `RECORD_COMPONENTS`,...

--------------------------------------------------------------------------
## Java Enhancement Proposals

reviewing JEP did not provide explicit guidance on possible checks that require updates to accommodate this new feature. 

---  
  ##  Similar and Related  Tokens

```
mahfouz@dell-g15:~$ grep -rl "PATTERN_VARIABLE_DEF" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ grep -rl "PATTERN_DEF" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ grep -rl "LITERAL_INSTANCEOF" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ grep -rl "RECORD_COMPONENT_DEF" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ grep -rl "RECORD_COMPONENTS" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ cat checks.txt | sort -u
```

- [x] coding/EqualsAvoidNullCheck.java https://github.com/checkstyle/checkstyle/issues/14952
- [x] coding/HiddenFieldCheck.java   https://github.com/checkstyle/checkstyle/issues/14964
- [x] coding/IllegalTypeCheck.java     https://github.com/checkstyle/checkstyle/issues/14946 
- [x] coding/MissingSwitchDefaultCheck.java    https://github.com/checkstyle/checkstyle/issues/14891 
- [x] coding/UnnecessaryParenthesesCheck.java https://github.com/checkstyle/checkstyle/issues/15003
- [x] naming/AbbreviationAsWordInNameCheck.java https://github.com/checkstyle/checkstyle/issues/15004
- [x] naming/IllegalIdentifierNameCheck.java  https://github.com/checkstyle/checkstyle/issues/15005
- [x] naming/PatternVariableNameCheck.java https://github.com/checkstyle/checkstyle/issues/15006
- [x] whitespace/GenericWhitespaceCheck.java https://github.com/checkstyle/checkstyle/issues/15008
- [x] whitespace/OperatorWrapCheck.java https://github.com/checkstyle/checkstyle/issues/15007

---
## Frequently Impacted Checks
- [x] [IllegalTokenText](https://checkstyle.org/checks/coding/illegaltokentext.html): no tokens text with this feature. We won't update this check
- [x]  [Indentation](https://checkstyle.org/checks/misc/indentation.html#Indentation): we need to open separate issue for this feature to see if we need to update it https://github.com/checkstyle/checkstyle/issues/15055
- [x]  [IllegalToken](https://checkstyle.org/checks/coding/illegaltoken.html): this check supports all tokens. It should be updated https://github.com/checkstyle/checkstyle/issues/15294
- [Whitespace](https://checkstyle.org/checks/whitespace/index.html) : 
  - [x]  [MethodParamPad](https://checkstyle.org/checks/whitespace/methodparampad.html#MethodParamPad): `RECORD_DEF` is supported in this check https://github.com/checkstyle/checkstyle/issues/14966
  - [x] [ParenPad](https://checkstyle.org/checks/whitespace/parenpad.html#ParenPad): the new syntax uses parentheses. https://github.com/checkstyle/checkstyle/issues/14948
  - [x] [NoWhitespaceAfter](https://checkstyle.org/checks/whitespace/nowhitespaceafter.html#NoWhitespaceAfter) : check that there is no whitespace between the record pattern and the next parenthesis `RecordPattern  (int x)` same as `LITERAL_SYNCHRONIZED` in this check
  https://github.com/checkstyle/checkstyle/issues/15009
---
## Other Static Analysis tool
- Intellij Inspection:
    - **([Condition is covered by further condition](https://www.jetbrains.com/help/inspectopedia/ConditionCoveredByFurtherCondition.html) -> null-check is redundant with instanceof operator**): this rule is not related to record patterns only. It should apply for any pattern matching with instanceof.  We can consider a new check `redundantNullCheckWithPatternMatching`
   - **[record pattern can be used](https://www.jetbrains.com/help/inspectopedia/DeconstructionCanBeUsed.html)**: this rule can't be applied due to a [limitation](https://checkstyle.org/writingchecks.html#Limitations). Checkstyle is not type-aware
 - PMD: I don't see any updates in rules just grammer and parser updates
 ---
## Good Source of Best Practices
- [Jetbrains blog](https://blog.jetbrains.com/idea/2022/11/java-19-and-intellij-idea/)
- [javaalmanac](https://javaalmanac.io/features/recordpatterns/)

the most encourged best practice stated for record pattern is to use it instead of the old destruction syntax. We can't make a check to enforce this because we are not type aware

---
## Associated JEP's Recommendations ([JEP 440](https://openjdk.org/jeps/440))

> If a record pattern names a generic record class but gives no type arguments (i.e., the record pattern uses a raw type) then the type arguments are always inferred. Inference works with nested record patterns. In fact it is possible to drop the type arguments in the outer record pattern as well, leading to the concise code

As of Java 21, type arguments for record patterns can be inferred by the compiler when not explicitly provided. JEP recommend to drop type arguments in record pattern as this leads to a more concise code. This guides us to consider implementing a new check named `UnnecessaryTypeArgumentsWithRecordPattern`

**JEP Code Example:**
```java
static void test2(Box<Box<String>> bbs) {
    if (bbs instanceof Box<Box<String>>(Box(var s))) {
        System.out.println("String " + s);
    }
    if (bbs instanceof Box(Box(var s))) {
        System.out.println("String " + s);  // Here the compiler will infer that the entire instanceof pattern is Box<Box<String>>(Box<String>(var s)
    }
}
---

```
 ---
 ## Discover Similar Checks
 We have a check that violate the parameter assignment. Paremeters assignment is often considered poor programming practice as it can lead to confusion and unexpected behavior. The same would apply to pattern variables.
We should consider implementing a new check similar to [ParameterAssignment](https://checkstyle.org/checks/coding/parameterassignment.html#ParameterAssignment) that violates the assignment of pattern variables

---

## Potential New Checks

The previously mentioned approaches' analysis has led to the proposal of the following new checks.

- [ ]  `RedundantNullCheckWithPatternMatching`:  Enforce removing redundant null checks when using instance of operator.
https://github.com/checkstyle/checkstyle/issues/14945
- [ ]  `PatternVariableAssignment`: Similar to the [ParameterAssignment](https://checkstyle.org/checks/coding/parameterassignment.html#ParameterAssignment) check, enforce best practices by disallowing assignments to pattern variables.
 https://github.com/checkstyle/checkstyle/issues/14949
- [ ]  `UnnecessaryTypeArgumentsWithRecordPattern`: Ensure type arguments are dropped in record patterns for conciseness. Given the fact that they are always inferred.
https://github.com/checkstyle/checkstyle/issues/15223

**Comment by nrmancuso** [comment]
I am removing approved label, we still have some work to do in description

**Comment by nrmancuso** [comment]
@mahfouz72 please do:
 - order this ticket the same way that we have https://github.com/checkstyle/checkstyle/blob/master/docs/NEW_LANGUAGE_FEATURE_INTEGRATION_PROCESS.md (please always do this)
 - why ParenPad and NoWhitespaceAfter? A short blurb about why would be good. I guess from the parenthesis that delimit the components?
 - link to the Intellij Inspections (it is good to reference any outside sources, always)
 - Did we check any of our sources for best practices?

**Comment by nrmancuso** [comment]
I am good to improve after:

 - Similar and Related Tokens, remove:
    - JavadocType
    - RecordComponentnName
 - Make section for new checks to make it obvious
    - add your check for pattern variable reassignment
    - add a check for if we have an unused pattern variable, that we suggest using an unnamed pattern instead
    - add your check about type parameters for record patterns

**Comment by mahfouz72** [comment]
> * add a check for if we have an unused pattern variable, that we suggest using an unnamed pattern instead

I was going to add this check under the unnamed pattern tracker issue rather than this one. Do you agree?

 apart from this all is done

**Comment by nrmancuso** [comment]
> > * add a check for if we have an unused pattern variable, that we suggest using an unnamed pattern instead
> 
> I was going to add this check under the unnamed pattern tracker issue rather than this one. Do you agree?
> 
> apart from this all is done

Makes sense to me! Let’s just make sure to make a note in that issue to add test inputs for record patterns too.

**Comment by nrmancuso** [comment]
@rnveach please approve if you are good, I am

**Comment by rnveach** [comment]
@mahfouz72 This tracker issue is now approved.

Please keep this issue up to date on what will be spawning connected to this issue from here on out. For example, now that this is approved I am expecting child issues to be opened for everything in `Potential New Checks`, `Frequently Impacted Checks`, and `Similar and Related Tokens` (unless I am missing something).

You may want to consider leaving spots to write in the issue numbers and cross out things as they are completed so we have full recording and accounting of what we are doing here and can help identify when this issue is "done".

**Comment by mahfouz72** [comment]
> You may want to consider leaving spots to write in the issue numbers and cross out things as they are completed so we have full recording and accounting of what we are doing here and can help identify when this issue is "done".

@rnveach please see the issue description I  updated it with the spawned issues so far. For `Similar and Related Tokens`  just putting a link beside the check name is a good way? or should I take all these checks and make something like a checklist at the end of the issue

**Comment by nrmancuso** [comment]
> > You may want to consider leaving spots to write in the issue numbers and cross out things as they are completed so we have full recording and accounting of what we are doing here and can help identify when this issue is "done".
> 
> @rnveach please see the issue description I updated it with the spawned issues so far. For `Similar and Related Tokens` just putting a link beside the check name is a good way? or should I take all these checks and make something like a checklist at the end of the issue

A checklist would be awesome

**Comment by mahfouz72** [comment]
@nrmancuso done please check if it is good

**Comment by nrmancuso** [comment]
@mahfouz72 please open remaining issues (UnnecessaryTypeArgumentsWithRecordPattern, IllegalToken)

**Comment by nrmancuso** [comment]
All child issues have been opened, we can close this issue now.
