### ISSUE TITLE
Add Check Support for Java 21 Pattern Matching for Switch Syntax

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14961]
This issue will be the main tracker of all the work related to [Pattern Matching for Switch](https://openjdk.org/jeps/441). It will involve updating existing checks to ensure they correctly handle this new syntax and analysis of possible static analysis coverage (new checks) for this new language feature.

---
new Tokens: `LITERAL_WHEN`
similar and related tokens: `LITERAL_IF`, `LITERAL_CASE`, `LAND`

---
## Java Enhancement Proposals 
reviewing JEP did not provide explicit guidance on possible checks that require updates to accommodate this new feature.

---
## Similar and Related Tokens

```
mahfouz@dell-g15:~$ grep -rl "LITERAL_IF" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ grep -rl "LAND" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ grep -rl "LITERAL_CASE" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ cat checks.txt | sort -u
```
- [x] blocks/EmptyBlockCheck.java  https://github.com/checkstyle/checkstyle/issues/15029
- [ ] blocks/LeftCurlyCheck.java https://github.com/checkstyle/checkstyle/issues/15032
- [x] blocks/NeedBracesCheck.java https://github.com/checkstyle/checkstyle/issues/15034
- [ ] blocks/RightCurlyCheck.java https://github.com/checkstyle/checkstyle/issues/15033
- [x] coding/DefaultComesLastCheck.java https://github.com/checkstyle/checkstyle/issues/15035
- [x] coding/FallThroughCheck.java https://github.com/checkstyle/checkstyle/issues/15038
- [x] coding/InnerAssignmentCheck.java  https://github.com/checkstyle/checkstyle/issues/15037
- [x] coding/NestedIfDepthCheck.java https://github.com/checkstyle/checkstyle/issues/15036
- [x] coding/SimplifyBooleanExpressionCheck.java https://github.com/checkstyle/checkstyle/issues/15039
- [x] coding/SimplifyBooleanReturnCheck.java  https://github.com/checkstyle/checkstyle/issues/15040
- [x] coding/UnnecessaryParenthesesCheck.java https://github.com/checkstyle/checkstyle/issues/14972
- [x] coding/VariableDeclarationUsageDistanceCheck.java  https://github.com/checkstyle/checkstyle/issues/15043
- [x] indentation/CaseHandler.java  => Check the Frequently Impacted Checks section to see the issue related to indentation of `when`, `case` and the things around it 
- [ ] indentation/CommentsIndentationCheck.java  https://github.com/checkstyle/checkstyle/issues/15049
- [x] indentation/HandlerFactory.java
- [x] indentation/IfHandler.java
- [x] indentation/LineWrappingHandler.java
- [x] indentation/MethodDefHandler.java
- [x] indentation/SlistHandler.java
- [x] indentation/SwitchRuleHandler.java
- [x] metrics/BooleanExpressionComplexityCheck.java  https://github.com/checkstyle/checkstyle/issues/15044
- [x] metrics/CyclomaticComplexityCheck.java  https://github.com/checkstyle/checkstyle/issues/15045
- [ ] metrics/JavaNCSSCheck.java  https://github.com/checkstyle/checkstyle/issues/15046
- [x] metrics/NPathComplexityCheck.java  https://github.com/checkstyle/checkstyle/issues/15047
- [x] whitespace/NoWhitespaceBeforeCaseDefaultColonCheck.java  https://github.com/checkstyle/checkstyle/issues/15048
- [ ] whitespace/OperatorWrapCheck.java https://github.com/checkstyle/checkstyle/issues/14962
- [x] whitespace/ParenPadCheck.java https://github.com/checkstyle/checkstyle/issues/14980
- [x] whitespace/WhitespaceAfterCheck.java   https://github.com/checkstyle/checkstyle/issues/15025
- [x] whitespace/WhitespaceAroundCheck.java https://github.com/checkstyle/checkstyle/issues/15027

---
## Frequently Impacted Checks
- [IllegalTokenText](https://checkstyle.org/checks/coding/illegaltokentext.html): no tokens text with this feature. We won't update this check.
- [Indentation](https://checkstyle.org/checks/misc/indentation.html#Indentation): We need to open a separate issue for this check to see if we need to update it. We may need a WhenHandler https://github.com/checkstyle/checkstyle/issues/14971
- [IllegalToken](https://checkstyle.org/checks/coding/illegaltoken.html): this check supports all tokens. It should be updated https://github.com/checkstyle/checkstyle/issues/15293
- [Whitespace](https://checkstyle.org/checks/whitespace/index.html): 
    - [WhiteSpaceAfter](https://checkstyle.org/checks/whitespace/whitespaceafter.html#WhitespaceAfter): To check spaces after when keyword example: `when(x>2)`   https://github.com/checkstyle/checkstyle/issues/15025
    - [WhiteSpaceAround](https://checkstyle.org/checks/whitespace/whitespacearound.html) may be considered too
      https://github.com/checkstyle/checkstyle/issues/15027

---
##  Other Static Analysis tool
- Intelliji Inspection: no new inspection rule for this new syntax. But there is a rule for switch in general which is [IfCanBeSwitch](https://www.jetbrains.com/help/inspectopedia/IfCanBeSwitch.html)
https://github.com/checkstyle/checkstyle/issues/15226

- Sonarlint: [Use when instead of a single if inside a pattern match body](https://rules.sonarsource.com/java/tag/java21/RSPEC-6916/)
https://github.com/checkstyle/checkstyle/issues/14985
---
## Good Source of Best Practices

- [Evolution of the Switch Construct in Java—Why Should you Care?
](https://blog.jetbrains.com/idea/2024/01/evolution-of-the-switch-construct-in-java-why-should-you-care/)

--- 
## Associated JEP's Recommendations

> Traditionally, switch statements and expressions throw NullPointerException if the selector expression evaluates to null, so testing for null must be done outside of the switch . This was reasonable when switch supported only a few reference types. However, if switch allows a selector expression of any reference type, and case labels can have type patterns, then the standalone null test feels like an arbitrary distinction which invites needless boilerplate and opportunities for error. It would be better to integrate the null test into the switch by allowing a new null case label

we should consider implementing a new check to violate switch cases with a reference types macthing that doesn't have `null` case label. By integrating the `null` case into the switch statement, we ensure that the code is cleaner as we don't have to make a null check outside the switch and eliminating the risk of `NullPointerException`

- [x] https://github.com/checkstyle/checkstyle/issues/14979

---
## Discover Similar Checks

We should have a `YieldCount` check similar to [ReturnCount](https://checkstyle.org/checks/coding/returncount.html#ReturnCount).  Since ReturnCount operates on the method level, YieldCount can operate only on the block level in a switch expression.

- [ ] https://github.com/checkstyle/checkstyle/issues/15052

**Comment by nrmancuso** [comment]
>The guarded patterns using && in switch have been modified to use when. we need to update an [old input file](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapGuardedPatterns.java) to use the new syntax.

As long as we support the `&&` syntax, we should not be changing input files. I kept support for this syntax since it was cheap and we made some other updates around it.

**Comment by nrmancuso** [comment]
>we need to update an [old input file](https://github.com/checkstyle/checkstyle/blob/master/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/checks/whitespace/operatorwrap/InputOperatorWrapGuardedPatterns.java) to use the new syntax.

Please remove this from the description.

@mahfouz72 please investigate the possibility of a new check to place violations on not declaring a `null` case in a switch with pattern matching. Will a switch with pattern matching throw a NPE on a null object?

**Comment by rnveach** [comment]
@mahfouz72 @nrmancuso 
> New Check MissingSwitchNullCase 

What about `NullCaseComesLast`?
https://checkstyle.org/checks/coding/defaultcomeslast.html#DefaultComesLast

**Comment by mahfouz72** [comment]
> What about `NullCaseComesLast`

I thought of this but what blocks me is what about there are both `case null` and `default` Who should come last? There will be a battle between the two checks.

**note:** When there are both, the default must come last otherwise the code won't compile
```
    public void test(Object obj) {
        switch (obj) {
            case Integer integer -> System.out.println("Integer");
             default -> System.out.println("default");
            case null -> System.out.println("null"); // compile error , dominated by a preceding 'default'
        }

    }
```
 
so the only thing that makes this check valid is to ask for `NullCaseComesLast` only if there is no default in the switch to avoid compiler error and conflict between both checks

**Comment by rnveach** [comment]
I was thinking it would either allow default to come after it or allow a property to choose it's placement. However, if it literally can't be last, then that shows where it would be placed in order. I just can't think of a proper name for it which would match or atleast be acceptable.

**Comment by nrmancuso** [comment]
So, with pattern matching for switch, order very much matters, and can be based on guards and dominance. I would hesitate to make any check that would demand a certain order for cases with pattern matching, since the compiler already does a great job of directing us where to place the `null` case. We will not do any better than the compiler. 

We only need a check to make sure that a null case is present, the compiler will do the rest.

**Comment by nrmancuso** [comment]
@rnveach I am good to approve if you are, please place the label once you are ready to party

**Comment by rnveach** [comment]
@mahfouz72 
> Other Static Analysis tool

I brought up sonarlint in discord recently. When are we reviewing it and seeing if it adds anything to our tracker issues?

**Comment by nrmancuso** [comment]
@rnveach @mahfouz72 are we good here?

**Comment by mahfouz72** [comment]
I am good

**Comment by rnveach** [comment]
I am good.

**Comment by rnveach** [comment]
@nrmancuso @mahfouz72 
Taken from https://github.com/checkstyle/checkstyle/issues/15029#issuecomment-2177544141 .

> case ColoredPoint(int x, _, _) when(x >= 2) -> { } 
> case ColoredPoint(int x, _, _) when(x >= 2) : { } break;

> or my clarity, what is the actual difference between using -> and : for the cases.
> as far as I know, the difference is : Requires break statements to prevent fall-through. while with -> no need for break statements and no fall-through. and in switch expressions -> can be used directly to return a value without the need for braces and a local variable.
> is this enough for a check to enforce users to use -> or : where it is better appropriate? Is there any best practice here?

What do we think of this being a new check?

**Comment by nrmancuso** [comment]
>What do we think of this being a new check?

Something like "If there is no fallthrough, you can use `->` instead of `:`"?

**Comment by rnveach** [comment]
Yes, or a check which allows users to force `:` or `->` based on their preference and what can be allowed from the current implementation (like skipping switches with fall throughs if they want to change `:` to `->`).

**Comment by nrmancuso** [comment]
Sounds like a great idea, I frequently find myself suggesting this in PR review elsewhere :)

**Comment by rnveach** [comment]
@nrmancuso Please clarify which direction we want to go. 

> a check which allows users to force : or -> based on their preference and what can be allowed from the current implementation 
> If there is no fallthrough, you can use -> instead of :"

Then let @mahfouz72 he can start an issue. I am more for customization how someone wants (first option), but I can understand if we want to guide user based on a specific need or practice (second option).

**Comment by nrmancuso** [comment]
@mahfouz72 looks like we don't have an issue for regular indentation yet, or am I missing it?

**Comment by mahfouz72** [comment]
[Indentation](https://checkstyle.org/checks/misc/indentation.html#Indentation): We need to open a separate issue for this check to see if we need to update it. We may need a WhenHandler https://github.com/checkstyle/checkstyle/issues/14971 you mean this?

**Comment by nrmancuso** [comment]
I have updated the checklist for indentation

**Comment by nrmancuso** [comment]
All child issues have been opened, we can close this issue now.
