### ISSUE TITLE
Add Check Support for Java 17 Sealed Classes

### ISSUE THREAD

**Issue by mahfouz72** [checkstyle/checkstyle#14969]
This issue will be the main tracker of all the work related to [Sealed Classes](https://openjdk.org/jeps/409). It will involve updating existing checks to ensure they correctly handle this new syntax and analysis of possible static analysis coverage (new checks) for this new language feature.

---
new tokens: `LITERAL_NON_SEALED`, `LITERAL_SEALED`,  `LITERAL_PERMITS`, `PERMITS_CLAUSE`
similar/related tokens: `LITERAL_PUBLIC`, `IMPLEMENTS_CLAUSE`

---
## Similar and Related Tokens
```
mahfouz@dell-g15:~$ grep -rl "IMPLEMENTS_CLAUSE" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ grep -rl "LITERAL_PUBLIC" $checks | cut -d/ -f14- >> checks.txt
mahfouz@dell-g15:~$ cat checks.txt | sort -u
```
- [x] annotation/AnnotationOnSameLineCheck.java https://github.com/checkstyle/checkstyle/issues/15074
- [x] annotation/MissingOverrideCheck.java https://github.com/checkstyle/checkstyle/issues/15075
- [x] coding/IllegalTypeCheck.java https://github.com/checkstyle/checkstyle/issues/15010
- [x] coding/VariableDeclarationUsageDistanceCheck.java https://github.com/checkstyle/checkstyle/issues/15076
- [x] design/OneTopLevelClassCheck.java https://github.com/checkstyle/checkstyle/issues/15077
- [x] metrics/ClassFanOutComplexityCheck.java https://github.com/checkstyle/checkstyle/issues/15078
- [x] modifier/InterfaceMemberImpliedModifierCheck.java https://github.com/checkstyle/checkstyle/issues/15079
- [x] modifier/RedundantModifierCheck.java https://github.com/checkstyle/checkstyle/issues/15087
- [x] naming/AbstractAccessControlNameCheck.java (This check for class fields naming so public there is a field not a class modifier)
- [x] OuterTypeFilenameCheck.java https://github.com/checkstyle/checkstyle/issues/15086
- [x] UncommentedMainCheck.java https://github.com/checkstyle/checkstyle/issues/15086

---
## Frequently Impacted Checks

- [IllegalTokenText](https://checkstyle.org/checks/coding/illegaltokentext.html): no tokens text with this feature. We won't update this check.
- [Indentation](https://checkstyle.org/checks/misc/indentation.html#Indentation): We need to open a separate issue for this check to see if we need to update it. https://github.com/checkstyle/checkstyle/issues/15108
- [IllegalToken](https://checkstyle.org/checks/coding/illegaltoken.html): this check supports all tokens. It should be updated https://github.com/checkstyle/checkstyle/issues/15296
- [Whitespace](https://checkstyle.org/checks/whitespace/index.html): https://github.com/checkstyle/checkstyle/issues/15297

---
## Other Static Analysis tool
- Intellij Inspection:
    - [Sealed should have explicit permits list ](https://www.jetbrains.com/help/inspectopedia/FillPermitsList.html): I think this gives us some idea about new check that violate usage of sealed classes without permits clause
    https://github.com/checkstyle/checkstyle/issues/14975
- Sonarlint: [Permitted types of a sealed class should be omitted if they are declared in the same file](https://rules.sonarsource.com/java/tag/java17/)
https://github.com/checkstyle/checkstyle/issues/14986

**Comment by rnveach** [comment]
> Similar and Related Tokens

https://checkstyle.org/checks/modifier/modifierorder.html#ModifierOrder check already supports this but it wasn't picked up by your scan. It just has the text form of the tokens, and not the `LITERAL_` portion.

**Comment by nrmancuso** [comment]
@mahfouz72 please convert all items to a checklist and elaborate on
>[subclasses are missing from permits clause ](https://www.jetbrains.com/help/inspectopedia/FillPermitsList.html): I think this gives us some idea about new check that violate usage of sealed classes without permits clause

**Comment by nrmancuso** [comment]
>[Whitespace](https://checkstyle.org/checks/whitespace/index.html): I don't think we need any updates here. If there is no space then the code won't compile

What about opening `{` after permits clause?

@mahfouz72 please finish opening issues

**Comment by mahfouz72** [comment]
> What about opening { after permits clause?

like this? This is a violation on `{` with whitespaceAround check. 
`public class A permits B{}`

**Comment by nrmancuso** [comment]
All child issues have been opened, we can close this issue now.
