### ISSUE TITLE
dependency: bump org.apache.maven.plugins:maven-site-plugin from 3.12.1 to 3.21.0

### ISSUE THREAD

**Issue by romani** [checkstyle/checkstyle#16077]
based on discussion at https://github.com/checkstyle/checkstyle/pull/15799
where update becomes too big to be done at ones, so we need to split update in few phases.

updates:
- ~remove usage of `xdocDirectory` property in plugin as it is deprecated;~ https://maven.apache.org/plugins-archives/maven-site-plugin-3.6/run-mojo.html#xdocDirectory , https://github.com/checkstyle/checkstyle/pull/15799#issuecomment-2562820592
- ~find way to use custom css and js files~
- ~usage of skin as artifact~
- ~migration to maven-site-plugin 3.21.0~
- [ ] enable xml plugin in pom.xml
- [ ] fix links in sun and Google style, remove them from suppression that we did in first PR
- [x] mobile web site should have tables to be single column.
- [x] non-formatted text should be wrapped , very visible in mobile mode. Attention to `<suppress checks="OrderedPropertie..` https://checkstyle.org/checks/misc/orderedproperties.html#Description vs https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/736f882_2025165436/checks/misc/orderedproperties.html#Example1-code
- [x] all table headers column text should be adjusted to left. Not a middle of cell. https://checkstyle.org/checks/misc/orderedproperties.html#Properties
- [x] code blocks should not be wrapped. Acute problem for mobile mode. https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/736f882_2025165436/checks/misc/orderedproperties.html#undefined
- [x] remove text links under banner images in left panel,  just image/banner is enough. https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/736f882_2025165436/index.html   
- [x] click on name of section use to update link in browser location to have full link with anchor. Kill feature for maintainers to share link to exact place in doc. Now it is generating `#undefined` https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/736f882_2025165436/checks/annotation/annotationlocation.html#undefined
- [x] no link images as first column, https://checkstyle.org/cmdline.html#Command_line_usage_Command_Line_Options vs https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/736f882_2025165436/cmdline.html
- [x] not clear why some text under section has different indentation from left - https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/077463c_2025133942/checks/annotation/annotationlocation.html#AnnotationLocation , search  for "Attention: Elements that cann...."
- [ ] in logs there are huge amount of WARNINGS like: `Anchor name "Description" used more than once`, ` Anchor name "Properties" used more than once`, ....
- [x] Make hamburger stick to the top, not done but not clear, non sticky is good .
- [ ] left panel links/text is not wrapped https://github.com/checkstyle/checkstyle/issues/16077#issuecomment-2602735431
- [x]  in mobile mode reduce left and right margin, to increase space for text as much as possible. Details https://github.com/checkstyle/checkstyle/issues/16077#issuecomment-2605240191
- [ ] header images is bigger than before and make redline is not touching top of page, [details](https://github.com/checkstyle/checkstyle/issues/16077#issuecomment-2607293605).
- [ ] tables headers text should aligned to top of cell, [details](https://github.com/checkstyle/checkstyle/issues/16077#issuecomment-2607327177). 
- [ ] make line spacing for code snippets (line height) to be compact, as in was in old website 
- [ ] code snippets have too much in top/bottom spacing [details](https://github.com/checkstyle/checkstyle/issues/16077#issuecomment-2614139913)

**Comment by romani** [comment]
Initial fix is merged, there will be several followup PR to fix each leftovers individually.

**Comment by Zopsss** [comment]
> non-formatted text should be wrapped , very visible in mobile mode. Attention to <suppress checks="OrderedPropertie..

&

> code blocks should not be wrapped. Acute problem for mobile mode.

both are fixed. Please mark them as done.

**Comment by Zopsss** [comment]
"Make hamburger stick to the top", please add this to todo list.

**Comment by Zopsss** [comment]
PR sent for following:

> click on name of section use to update link in browser location to have full link with anchor. Kill feature for maintainers to share link to exact place in doc. Now it is generating #15584 

https://github.com/checkstyle/checkstyle/pull/16185

**Comment by romani** [comment]
>Make hamburger stick to the top

I might misunderstood this, but I like the way it scrolled out, it give more space for content, we have toTop button, so it is not an issue.

**Comment by Zopsss** [comment]
PR sent for following:

> all table headers column text should be adjusted to left. Not a middle of cell.

https://github.com/checkstyle/checkstyle/pull/16197

**Comment by Zopsss** [comment]
pr sent for following:

> no link images as first column

https://github.com/checkstyle/checkstyle/pull/16198

**Comment by romani** [comment]
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/93a3bed_20250120141202/filters/suppresswithplaintextcommentfilter.html#Example1-config

![Image](https://github.com/user-attachments/assets/19fb2fba-3e25-4bd6-8a53-4d83d53205c6)

**Comment by Zopsss** [comment]
PR sent for following:

> remove text links under banner images in left panel, just image/banner is enough. 

https://github.com/checkstyle/checkstyle/pull/16213

**Comment by Zopsss** [comment]
PR sent for following:

> mobile web site should have tables to be single column.

https://github.com/checkstyle/checkstyle/pull/16212

**Comment by romani** [comment]
New website has too big margins:
Old:
![Image](https://github.com/user-attachments/assets/c5f16d22-caf4-4387-8c77-efffb1bf9df5)
New:
![Image](https://github.com/user-attachments/assets/46f23c79-3ec7-41f3-ac06-a0a2c3c13532)

**Comment by romani** [comment]
header image is extra big, by height:
old side:

![Image](https://github.com/user-attachments/assets/e8fcc10d-49a5-49f5-a063-f079872c97b4)

**Comment by romani** [comment]
table headers should be aligned to top of cell, old website:
![Image](https://github.com/user-attachments/assets/bad2a64f-dec8-45af-93a2-44e58e6623c6)

**Comment by romani** [comment]
https://checkstyle.org/checks/annotation/annotationlocation.html
https://checkstyle-diff-reports.s3.us-east-2.amazonaws.com/2c99642_20250123190805/checks/annotation/annotationlocation.html#Description

![Image](https://github.com/user-attachments/assets/3951f0a8-2f7e-4908-b0c9-9d1955fe889e)

![Image](https://github.com/user-attachments/assets/6b8036e0-8323-4259-a997-a6d46b133f20)

Code snippets have too much spaces on top and bottom, we should make it compact as it was before.

**Comment by romani** [comment]
closing this big issue 

new issues:
https://github.com/checkstyle/checkstyle/issues/16242
https://github.com/checkstyle/checkstyle/issues/16243

**Comment by romani** [comment]
We need to change "until" comments that are pointing to this issue, to be #16242

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/commit/a0d914256696c088cad3f352111f3e262771ce19 done
