### ISSUE TITLE
set up JDK11 build

### ISSUE THREAD

**Issue by pbludov** [checkstyle/checkstyle#6228]
Java 11 was released recently. And CI (at least Travis/AppVeyor) already has ability to build the Checkstyle with JDK11.

But the Checkstyle build with jdk 11 is broken. It requires a bit of minor changes in the code to fix:

- [x] PowerMock library version is outdated and should be updated (#6238);
- [x] The `PackageObjectFactoryTest` should be rewritten. It is not possible to throw an undeclared exception from a mocked method anymore, so `when(classLoader.getURLs()).thenThrow(IOException.class)` fails (#6238);
- [x] `javax.annotation.Generated` annotation was removed in favor of `javax.annotation.processing.Generated` (#6252);
- [x] all `sun.*` packages were completely removed (#6252);
- [x] replace `<table summary="text">` with `<table><caption>text</caption>` in javadoc (#5750);
- [x] In the `ConfigurationLoaderTest` an exception message was changed (#6310);
- [ ] add java1x parser tests and javac{10..11} to travis.sh

**Comment by romani** [comment]
users become interested in this update - https://groups.google.com/forum/#!topic/checkstyle/TkYObZFOd6o

**Comment by rnveach** [comment]
I assume this closes the issue?

**Comment by romani** [comment]
> add java1x parser tests and javac{10..11} to travis.sh

is moved to #6316
